from enum import Enum
from pydantic import BaseModel, Field
from datetime import datetime

from business_logic.metamessage import MessageTypeEnum, MessagePriorityEnum

EMAIL_REGEX = r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'

class MessageType(Enum):
    INCOMING = "incoming"
#    OUTGOING = "outgoing"

class Events(Enum):
    MESSAGE_CREATED = 'message_created'
    MESSAGE_UPDATED = 'message_updated'
#    CONVERSATION_STATUS_CHANGED = 'conversation_status_changed'
#    CONVERSATION_UPDATED = 'conversation_updated'
#    CONVERSATION_CREATED = 'conversation_created'
#    CONTACT_CREATED = 'contact_created'
#    CONTACT_UPDATED = 'contact_updated'
#    WEBWIDGET_TRIGGERED = 'webwidget_triggered'
#    INBOX_CREATED = 'inbox_created'
#    INBOX_UPDATED = 'inbox_updated'
#    CONVERSATION_TYPING_ON = 'conversation_typing_on'
#    CONVERSATION_TYPING_OFF = 'conversation_typing_off'


class ConversationSubRequest(BaseModel):
    id: int = Field(..., title="Conversation's ID")
    status: str = Field(..., max_length=255, title="Conversation's status")
    inbox_id: str | None = Field(title="Conversation's attached inbox_id")

class SenderSubRequest(BaseModel):
    id: int = Field(..., title="Sender's ID")
    name: str = Field(..., max_length=255, title="Sender's name")
    email: str = Field(..., pattern=EMAIL_REGEX, title="Sender's email")

class AccountSubRequest(BaseModel):
    id: int = Field(..., title="Account's ID")
    name: str = Field(..., max_length=255, title="Account's name")

class ChatRequest(BaseModel):
    event: Events = Field(..., title="Triggered event")
    id: int = Field(..., title="Request's ID")
    content: str = Field(..., title="Request's content")
    created_at: datetime = Field(..., title="Datetime created at")
    message_type: MessageType = Field(..., title="Message type")
    conversation: ConversationSubRequest = Field(..., title="Conversation")
    sender: SenderSubRequest = Field(..., title="Sender")
    account: AccountSubRequest = Field(..., title="Account")

class MessageResponse(BaseModel):
    response_message: str = Field(..., title="Response message", description="LLM genereted response")
    tags: list[str] = Field(..., title="Tags", description="List of tags (keywords) generated by LLM")
    priority: str = Field(..., title="Priority", description="Priority of the last user message in the conversation", examples=[
            MessagePriorityEnum.LOW, MessagePriorityEnum.AVERAGE, MessagePriorityEnum.HIGH, MessagePriorityEnum.CRITICAL
        ])
    msg_type: str = Field(..., title="Message type", description="Type of the last user message in the conversation", examples=[
            MessageTypeEnum.PAYMENT, MessageTypeEnum.AUTORIZATION, MessageTypeEnum.BUG, MessageTypeEnum.FAQ
        ])

